services:
  postgres:
    image: postgres:16-alpine
    container_name: dmarc-postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-dmarc}
    volumes:
      - dmarc_postgres_data:/var/lib/postgresql/data
    networks:
      - dmarc-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    image: ghcr.io/samuelba/dmarc-report-visualizer/dmarc-backend:latest
    container_name: dmarc-backend
    environment:
      # Application Configuration
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}

      # Database Configuration
      DATABASE_HOST: ${DATABASE_HOST:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-dmarc}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE:-false}
      DB_MIGRATIONS_RUN: ${DB_MIGRATIONS_RUN:-true}

      # Backup Configuration
      BACKUP_DIR: ${BACKUP_DIR:-/app/backups}
      BACKUP_MANDATORY: ${BACKUP_MANDATORY:-true}
      BACKUP_KEEP_COUNT: ${BACKUP_KEEP_COUNT:-10}

      # CORS Configuration
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost}

      # Reprocessing Configuration
      REPROCESSING_WORKERS: ${REPROCESSING_WORKERS:-}

      # File Watcher Configuration
      ENABLE_FILE_WATCHER: ${ENABLE_FILE_WATCHER:-false}
      FILE_WATCH_DIR: ${FILE_WATCH_DIR:-reports/incoming}
      FILE_WATCH_DELETE_PROCESSED: ${FILE_WATCH_DELETE_PROCESSED:-true}
      FILE_WATCH_VERBOSE: ${FILE_WATCH_VERBOSE:-false}

      # Gmail Downloader Configuration
      ENABLE_GMAIL_DOWNLOADER: ${ENABLE_GMAIL_DOWNLOADER:-false}
      GMAIL_AUTH_MODE: ${GMAIL_AUTH_MODE:-oauth}

      # Gmail OAuth Configuration
      GMAIL_OAUTH_CLIENT_ID: ${GMAIL_OAUTH_CLIENT_ID:-}
      GMAIL_OAUTH_CLIENT_SECRET: ${GMAIL_OAUTH_CLIENT_SECRET:-}
      GMAIL_OAUTH_REFRESH_TOKEN: ${GMAIL_OAUTH_REFRESH_TOKEN:-}
      GMAIL_OAUTH_REDIRECT_URI: ${GMAIL_OAUTH_REDIRECT_URI:-http://localhost}

      # Gmail Service Account Configuration
      GMAIL_CLIENT_EMAIL: ${GMAIL_CLIENT_EMAIL:-}
      GMAIL_PRIVATE_KEY: ${GMAIL_PRIVATE_KEY:-}
      GMAIL_DELEGATED_USER: ${GMAIL_DELEGATED_USER:-}
      GMAIL_CREDENTIALS_JSON_PATH: ${GMAIL_CREDENTIALS_JSON_PATH:-}

      # Gmail Labels Configuration
      GMAIL_LABEL: ${GMAIL_LABEL:-DMARC Reports}
      GMAIL_PROCESSED_LABEL: ${GMAIL_PROCESSED_LABEL:-DMARC Processed}
      GMAIL_FAILED_LABEL: ${GMAIL_FAILED_LABEL:-DMARC Failed}

      # Gmail Processing Configuration
      GMAIL_POLL_INTERVAL_MS: ${GMAIL_POLL_INTERVAL_MS:-300000}
      GMAIL_LIST_PAGE_SIZE: ${GMAIL_LIST_PAGE_SIZE:-100}
      GMAIL_QUERY: ${GMAIL_QUERY:-has:attachment newer_than:5d -label:"DMARC Processed"}
      GMAIL_PROCESS_INLINE: ${GMAIL_PROCESS_INLINE:-true}
      GMAIL_SAVE_ORIGINAL: ${GMAIL_SAVE_ORIGINAL:-false}
      GMAIL_REMOVE_SOURCE_LABEL: ${GMAIL_REMOVE_SOURCE_LABEL:-true}
      GMAIL_FAILURE_THRESHOLD: ${GMAIL_FAILURE_THRESHOLD:-3}

      # IP Lookup Configuration
      IP_LOOKUP_PROVIDER: ${IP_LOOKUP_PROVIDER:-ip-api}
      IPLOCATE_API_KEY: ${IPLOCATE_API_KEY}
      IPAPICO_API_KEY: ${IPAPICO_API_KEY}
      IPWHOIS_API_KEY: ${IPWHOIS_API_KEY}
      IP_LOOKUP_FALLBACK_PROVIDERS: ${IP_LOOKUP_FALLBACK_PROVIDERS:-ipwhois,ip-api,ipapi-co,geoip-lite}
      IP_LOOKUP_CACHE_DAYS: ${IP_LOOKUP_CACHE_DAYS:-14}
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./backups:/app/backups
    networks:
      - dmarc-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    image: ghcr.io/samuelba/dmarc-report-visualizer/dmarc-frontend:latest
    container_name: dmarc-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - dmarc-network
    restart: unless-stopped

networks:
  dmarc-network:
    driver: bridge

volumes:
  dmarc_postgres_data:
